---
title: "Reproducible Research: Peer Assessment 1"
output: github_document
---


## Loading and preprocessing the data

Load the data (i.e. read.csv()). 

The data is stored in a single csv file zipped up in "activity.zip".

```{R Load Data}
mydata <- read.csv(unz("activity.zip","activity.csv"),header=T, quote="\"", sep=",")
head(mydata,5)
```

Process/transform the data (if necessary) into a format suitable for your analysis. Convert the date variable into dates.

```{R Convert to date}
mydata$date <- as.Date(mydata$date)
```

## What is mean total number of steps taken per day?

Calculate the total number of steps taken per day. Save the output into a table named mydata_bydate so that we can use it to plot a histogram in the next step.

```{R Create mydata_bydate}
mydata_bydate <- aggregate(mydata$steps, by=list(mydata$date), sum, na.rm = TRUE)
colnames(mydata_bydate) <- c("date","tot.nbr.of.steps")
mydata_bydate
```

If you do not understand the difference between a histogram and a barplot, research the difference between them. Make a histogram of the total number of steps taken each day.

```{R Plot histogram}
hist(mydata_bydate$tot.nbr.of.steps, main="Histogram of Total Number of Steps Taken Each Day", xlab="Total Number of Steps Taken Each Day")
```

Calculate and report the mean and median of the total number of steps taken per day

```{R Calc mean and median}
mymean <- mean(mydata_bydate$tot.nbr.of.steps, na.rm = TRUE)
mymean
mymedian <- median(mydata_bydate$tot.nbr.of.steps, na.rm = TRUE)
mymedian
```

The mean number of steps taken per day is `R mymean`.
The median number of steps taken per day is `R mymedian`.

## What is the average daily activity pattern?

Make a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)

```{R Time Series plot}
mydata_byinterval <- aggregate(mydata$steps, by=list(mydata$interval), mean, na.rm = TRUE)
colnames(mydata_byinterval) <- c("interval","avg.nbr.of.steps")

plot(mydata_byinterval, type = "l", main="Time Series of Average Number of Steps Taken", xlab="5-minute interval", ylab = "Average Number of Steps Taken")
```

Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

```{R Calc max}
mymax <- max(mydata_byinterval$avg.nbr.of.steps, na.rm = TRUE)
mymax
myinterval <- mydata_byinterval[mydata_byinterval$avg.nbr.of.steps == mymax, 1]
myinterval
```

Interval `R myinterval`, on average, contains the maximum number of steps at `R mymax` steps.

## Imputing missing values

Calculate and report the total number of missing values in the dataset (i.e. the total number of rows with NAs)

```{R Calc na}
myna <- sum(is.na(mydata$steps))
myna
```

There are `R myna` missing values in the dataset.

Devise a strategy for filling in all of the missing values in the dataset. The strategy does not need to be sophisticated. For example, you could use the mean/median for that day, or the mean for that 5-minute interval, etc.
Create a new dataset that is equal to the original dataset but with the missing data filled in. 

Use the mean for the day to replace NA values. If the mean for the day is not available, use 0. This new dataset is named mydata_noNA.

```{R Fill in NA}
##  First create a summary of the mean number of steps by date
mydata_means <- aggregate(mydata$steps, by=list(mydata$date), mean, na.rm = TRUE)
colnames(mydata_means) <- c("date","avg.nbr.of.steps")

## Fill in zero if mean is not available
mydata_means[is.na(mydata_means$avg.nbr.of.steps),"avg.nbr.of.steps"] <- 0

## Merge the average back into the main dataset
mydata_noNA <- merge(mydata, mydata_means, by = "date")

## Fill in the NAs
mynas <- is.na(mydata_noNA$steps)
mydata_noNA[mynas,"steps"] <- mydata_noNA[mynas,"avg.nbr.of.steps"]

```

Make a histogram of the total number of steps taken each day and Calculate and report the mean and median total number of steps taken per day. 

```{R Plot histogram again}
mydata_noNA_bydate <- aggregate(mydata_noNA$steps, by=list(mydata$date), sum)
colnames(mydata_noNA_bydate) <- c("date","tot.nbr.of.steps")

hist(mydata_noNA_bydate$tot.nbr.of.steps, main="Histogram of Total Number of Steps Taken Each Day", xlab="Total Number of Steps Taken Each Day")
```

```{R calc new mean and median}
mymean_noNA <- mean(mydata_noNA_bydate$tot.nbr.of.steps, na.rm = TRUE)
mymean_noNA
mymedian_noNA <- median(mydata_noNA_bydate$tot.nbr.of.steps, na.rm = TRUE)
mymedian_noNA
```

The new mean number of steps taken per day is `R mymean_noNA`.
The new median number of steps taken per day is `R mymedian_noNA`.

Do these values differ from the estimates from the first part of the assignment? What is the impact of imputing missing data on the estimates of the total daily number of steps?

No, because I used the mean value by date to replace the NAs. These new values are same as before. There is no impact to the estimates using this method of imputing missing data.

## Are there differences in activity patterns between weekdays and weekends?

Create a new factor variable in the dataset with two levels ??? ???weekday??? and ???weekend??? indicating whether a given date is a weekday or weekend day.

```{R weekday vs weekend}
is.weekend <- weekdays(mydata$date) %in% c("Saturday","Sunday")
mydata$dayofweek <- factor(c("weekday"), levels = c("weekday","weekend"))
mydata[is.weekend,"dayofweek"] <- factor(c("weekend"))
```

Make a panel plot containing a time series plot (i.e. type = "l") of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all weekday days or weekend days (y-axis). See the README file in the GitHub repository to see an example of what this plot should look like using simulated data.

```{R Time Series plots}
mydata_byinterval_plot <- aggregate(steps ~ interval + dayofweek, mydata, mean, na.rm = TRUE)

library(lattice)

xyplot(mydata_byinterval_plot$steps ~ mydata_byinterval_plot$interval | mydata_byinterval_plot$dayofweek, type = "l", layout = c(1,2), main="Time Series of Average Number of Steps Taken", xlab="5-minute interval", ylab = "Average Steps Taken")
```